### ISSUE TITLE
Issue: KDTreeObject are inserted to a kdTree but the map inside the kdTree is empty

### ISSUE THREAD

**Issue by GauravWalia19** [thegeekyasian/geo-assist#17]
See the below code

```java
KDTree<Integer, Object> kdTree = new KDTree<>();
kdTree.insert(new KDTreeObject.Builder<Integer, Object>().latitude(25.2002450).longitude(55.2734184).build());
kdTree.insert(new KDTreeObject.Builder<Integer, Object>().latitude(35.2002450).longitude(95.2734184).build());
kdTree.insert(new KDTreeObject.Builder<Integer, Object>().latitude(45.2002450).longitude(15.2734184).build());       
```

Now in the memory the kdTree will have
- `root` with the tree
- `size`
- **empty map**

Here I guess we shouldn't allow user to build the KDTreeObject without an id

**Comment by thegeekyasian** [comment]
Thanks for the feedback @GauravWalia19 
This is the intended behavior.

The intention behind the map is to get the value based on ID with the time-complexity of O(n).
Since there is no ID provided, the `getByID()` feature wouldn't return anything in that case.

Does that make sense?

**Comment by GauravWalia19** [comment]
This makes sense, but maybe we shouldn't allow user to build a `KDTreeObject` without id in first place

**Comment by thegeekyasian** [comment]
> This makes sense, but maybe we shouldn't allow user to build a `KDTreeObject` without id in first place

I completely get your point, but we will restrict the users from using the tree in the first place then. There could be some cases where users don't have an ID reference to the object in the first place. They might be using other (persistent) data sources to get such details.

This behavior is supported to unblock the user from using the KDTree, and restricting certain features instead for example `getByID()` or `deleteByID()`
