### ISSUE TITLE
Feature Request: Find the one very nearest neighbour

### ISSUE THREAD

**Issue by OmarHawk** [thegeekyasian/geo-assist#19]
Hi,

I'd like to use the library to search for the one element that is nearest to given input coordinates within the KDTree (searching the complete tree basically).

**Comment by thegeekyasian** [comment]
Thanks, @OmarHawk 

So you want a feature to find the nearest-most object, based on the distance from the total objects, right?
Please correct me if I have misunderstood the request.

**Comment by OmarHawk** [comment]
yes, input would be only a Point and expected result would *not* be a List<KDTreeObject> (compared to the findNearestNeighbor method), but just one single KDTreeObject (or empty Optional / null, if tree is empty)

**Comment by thegeekyasian** [comment]
Good thing that I already had a plan for this, but wasn't prioritized yet.

Thank you for creating an issue here @OmarHawk, let me work on this during next week and we shall support it in the upcoming version.

**Comment by thegeekyasian** [comment]
Hey @OmarHawk. I have created a PR for this feature request. This shall be made a part of the next release. (1.0.4).

I am planning to release it soon though.

**Comment by thegeekyasian** [comment]
@OmarHawk please note that the [release](https://central.sonatype.com/artifact/com.thegeekyasian/geo-assist/1.0.4) `1.0.4` is available now.

Please refer to the [documentation](https://github.com/thegeekyasian/geo-assist#find-the-nearest-most-neighbor) for the usage of the requested API.
